version: '3.8'

volumes:
  postgres_data:

services:

  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env