const config = require('../configs/appConfig');
const app = require('express')();
//const helmet = require("helmet");
const router = require('./routes');
const jsonParser = require('express').json();
const prismaErrorHandler = require('../prisma/middlewares/prismaErrorHandler');
const errorHandler = require('./middlewares/errorHandler');
const auth = require('../users/middlewares/auth');
const initSocket = require('../chat/webSoket');
//app.use(helmet());
app.use(jsonParser);
app.use(auth);
app.use(router);
app.use(prismaErrorHandler);
app.use(errorHandler);
const server = app.listen(config.server.port);
initSocket(server);