const config = require('../configs/appConfig');
const app = require('express')();
//const helmet = require("helmet");
const router = require('./routes');
const jsonParser = require('express').json();
//const prismaErrorHandler = require('../chat/middlewares/prismaErrorHandler');
const errorHandler = require('./middlewares/errorHandler');
const auth = require('../users/middlewares/auth');
//app.use(helmet());
app.use(jsonParser);
app.use(auth);
app.use(router);
app.use(errorHandler);
app.listen(config.server.port);